name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bash
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          install: bash coreutils

      - name: Run lint
        run: bash ci/lint.sh

      - name: Run tests
        run: bash ci/test.sh
